#
# Rivet Proxy
#  This is the main configuration file for proxies. If you don't already have a
#  game made, create on at https://hub.rivet.gg/
#

# The token for the game, you can find this on the API section of the game dashboard.
token: pub_rivet_token

# The environment is to dictate weather or not to use Rivet Cloud or a self-hosted Rivet instance.
# If you're using cloud, you can leave it as the default (PRODUCTION), however if you're trying
# to use a self-hosted instance, you'll need to change this to have a few more details.
#
# The following values are required when running a self-hosted instance, the
# default values for the cloud ran instance are provided:
#
# admin: https://admin.api.rivet.gg/v1
# auth: https://auth.api.rivet.gg/v1
# chat: https://chat.api.rivet.gg/v1
# cloud: https://cloud.api.rivet.gg/v1
# group: https://group.api.rivet.gg/v1
# identity: https://identity.api.rivet.gg/v1
# job: https://job.api.rivet.gg/v1
# kv: https://kv.api.rivet.gg/v1
# matchmaker: https://matchmaker.api.rivet.gg/v1
# party: https://party.api.rivet.gg/v1
# portal: https://portal.api.rivet.gg/v1
#
# Here is an example of a self-hosted instance:
# environment:
#   admin: https://admin.example.com/v1
#   auth: https://auth.example.com/v1
#   chat: https://chat.example.com/v1
#   cloud: https://cloud.example.com/v1
#   group: https://group.example.com/v1
#   identity: https://identity.example.com/v1
#   job: https://job.example.com/v1
#   kv: https://kv.example.com/v1
#   matchmaker: https://matchmaker.example.com/v1
#   party: https://party.example.com/v1
#   portal: https://portal.example.com/v1
#
environment: PRODUCTION
